
let colors = [
	// Standard colors
	{ label: 'Black', value: 0 },
	{ label: 'Graphite Black', value: 1 },
	{ label: 'Black Steel', value: 2 },
	{ label: 'Dark Silver', value: 3 },
	{ label: 'Silver', value: 4 },
	{ label: 'Blue Silver', value: 5 },
	{ label: 'Steel Gray', value: 6 },
	{ label: 'Shadow Silver', value: 7 },
	{ label: 'Stone Silver', value: 8 },
	{ label: 'Midnight Silver', value: 9 },
	{ label: 'Gun Metal', value: 10 },
	{ label: 'Anthracite Grey', value: 11 },
	{ label: 'Red', value: 27 },
	{ label: 'Torino Red', value: 28 },
	{ label: 'Formula Red', value: 29 },
	{ label: 'Blaze Red', value: 30 },
	{ label: 'Graceful Red', value: 31 },
	{ label: 'Garnet Red', value: 32 },
	{ label: 'Desert Red', value: 33 },
	{ label: 'Cabernet Red', value: 34 },
	{ label: 'Candy Red', value: 35 },
	{ label: 'Sunrise Orange', value: 36 },
	{ label: 'Classic Gold', value: 37 },
	{ label: 'Orange', value: 38 },
	{ label: 'Dark Green', value: 49 },
	{ label: 'Racing Green', value: 50 },
	{ label: 'Sea Green', value: 51 },
	{ label: 'Olive Green', value: 52 },
	{ label: 'Green', value: 53 },
	{ label: 'Gasoline Green', value: 54 },
	{ label: 'Midnight Blue', value: 61 },
	{ label: 'Dark Blue', value: 62 },
	{ label: 'Saxon Blue', value: 63 },
	{ label: 'Blue', value: 64 },
	{ label: 'Mariner Blue', value: 65 },
	{ label: 'Harbor Blue', value: 66 },
	{ label: 'Diamond Blue', value: 67 },
	{ label: 'Surf Blue', value: 68 },
	{ label: 'Nautical Blue', value: 69 },
	{ label: 'Bright Blue', value: 70 },
	{ label: 'Purple Blue', value: 71 },
	{ label: 'Spinnaker Blue', value: 72 },
	{ label: 'Ultra Blue', value: 73 },
	{ label: 'Bright Blue', value: 74 },
	{ label: 'Taxi Yellow', value: 88 },
	{ label: 'Race Yellow', value: 89 },
	{ label: 'Bronze', value: 90 },
	{ label: 'Yellow Bird', value: 91 },
	{ label: 'Lime', value: 92 },
	{ label: 'Champagne', value: 93 },
	{ label: 'Pueblo Beige', value: 94 },
	{ label: 'Dark Ivory', value: 95 },
	{ label: 'Choco Brown', value: 96 },
	{ label: 'Golden Brown', value: 97 },
	{ label: 'Light Brown', value: 98 },
	{ label: 'Straw Beige', value: 99 },
	{ label: 'Moss Brown', value: 100 },
	{ label: 'Bison Brown', value: 101 },
	{ label: 'Beechwood', value: 102 },
	{ label: 'Dark Beechwood', value: 103 },
	{ label: 'Choco Orange', value: 104 },
	{ label: 'Beach Sand', value: 105 },
	{ label: 'Sun Bleached Sand', value: 106 },
	{ label: 'Cream', value: 107 },
	{ label: 'Ice White', value: 111 },
	{ label: 'Frost White', value: 112 },
	{ label: 'Securicor Green', value: 125 },
	{ label: 'Police Car Blue', value: 127 },
	{ label: 'Pure White', value: 134 },
	{ label: 'Hot Pink', value: 135 },
	{ label: 'Salmon pink', value: 136 },
	{ label: 'Vermillion Pink', value: 137 },
	{ label: 'Orange', value: 138 },
	{ label: 'Green', value: 139 },
	{ label: 'Blue', value: 140 },
	{ label: 'Black Blue', value: 141 },
	{ label: 'Black Purple', value: 142 },
	{ label: 'Black Red', value: 143 },
	{ label: 'Hunter Green', value: 144 },
	{ label: 'Purple', value: 145 },
	{ label: 'V Dark Blue', value: 146 },
	{ label: 'Modshop Black 1', value: 147 },
	{ label: 'Lava Red', value: 150 },
	{ label: 'Default Alloy', value: 156 },
	{ label: 'Epsilon Blue', value: 157 },
	// Metalic colors
	{ label: 'Metalic Brushed Steel', value: 117 },
	{ label: 'Metalic Brushed Black Steel', value: 118 },
	{ label: 'Metalic Brushed Aluminum', value: 119 },
	{ label: 'Metalic Pure Gold', value: 158 },
	{ label: 'Metalic Brushed Gold', value: 159 },
	// Matte colors
	{ label: 'Matte Black', value: 12 },
	{ label: 'Matte Gray', value: 13 },
	{ label: 'Matte Light Gray', value: 14 },
	{ label: 'Matte Ice White', value: 131 },
	{ label: 'Matte Blue', value: 83 },
	{ label: 'Matte Dark Blue', value: 82 },
	{ label: 'Matte Midnight Blue', value: 84 },
	{ label: 'Matte Dark Purple', value: 149 },
	{ label: 'Matte Purple', value: 148 },
	{ label: 'Matte Red', value: 39 },
	{ label: 'Matte Dark Red', value: 40 },
	{ label: 'Matte Orange', value: 41 },
	{ label: 'Matte Yellow', value: 42 },
	{ label: 'Matte Lime Green', value: 55 },
	{ label: 'Matte Green', value: 128 },
	{ label: 'Matte Brown', value: 129 },
	{ label: 'Matte Forest Green', value: 151 },
	{ label: 'Matte Foilage Green', value: 155 },
	{ label: 'Matte Olive Drab', value: 152 },
	{ label: 'Matte Desert Brown', value: 153 },
	{ label: 'Matte Desert Tan', value: 154 },
	{ label: 'Matte White', value: 131 },
	// utility colors
	{ label: 'Black', value: 15 },
	{ label: 'Black Poly', value: 16 },
	{ label: 'Dark Silver', value: 17 },
	{ label: 'Silver', value: 18 },
	{ label: 'Gun Metal', value: 19 },
	{ label: 'Shadow Silver', value: 20 },
	{ label: 'Red', value: 43 },
	{ label: 'Bright Red', value: 44 },
	{ label: 'Garnet Red', value: 45 },
	{ label: 'Dark Green', value: 56 },
	{ label: 'Green', value: 57 },
	{ label: 'Dark Blue', value: 75 },
	{ label: 'Midnight Blue', value: 76 },
	{ label: 'Blue', value: 77 },
	{ label: 'Sea Foam Blue', value: 78 },
	{ label: 'Lightning blue', value: 79 },
	{ label: 'Maui Blue Poly', value: 80 },
	{ label: 'Bright Blue', value: 81 },
	{ label: 'Brown', value: 108 },
	{ label: 'Medium Brown', value: 109 },
	{ label: 'Light Brown', value: 110 },
	{ label: 'Off White', value: 122 },
	// Worn colors
	{ label: 'Worn Black', value: 21 },
	{ label: 'Worn Graphite', value: 22 },
	{ label: 'Worn Silver Grey', value: 23 },
	{ label: 'Worn Silver', value: 24 },
	{ label: 'Worn Blue Silver', value: 25 },
	{ label: 'Worn Shadow Silver', value: 26 },
	{ label: 'Worn Red', value: 46 },
	{ label: 'Worn Golden Red', value: 47 },
	{ label: 'Worn Dark Red', value: 48 },
	{ label: 'Worn Dark Green', value: 58 },
	{ label: 'Worn Green', value: 59 },
	{ label: 'Worn Sea Wash', value: 60 },
	{ label: 'Worn Dark Blue', value: 85 },
	{ label: 'Worn Blue', value: 86 },
	{ label: 'Worn Light blue', value: 87 },
	{ label: 'Worn Honey Beige', value: 113 },
	{ label: 'Worn Brown', value: 114 },
	{ label: 'Worn Dark Brown', value: 115 },
	{ label: 'Worn Straw Beige', value: 116 },
	{ label: 'Worn Off White', value: 121 },
	{ label: 'Worn Orange', value: 123 },
	{ label: 'Worn Light Orange', value: 124 },
	{ label: 'Worn Taxi Yellow', value: 126 },
	{ label: 'Worn White', value: 132 },
	{ label: 'Worn Olive Army Green', value: 133 },
	// chameleon colors
	{ label: 'Anodized Red', value: 161 },
	{ label: 'Anodized Wine', value: 162 },
	{ label: 'Anodized Purple', value: 163 },
	{ label: 'Anodized Blue', value: 164 },
	{ label: 'Anodized Green', value: 165 },
	{ label: 'Anodized Lime', value: 166 },
	{ label: 'Anodized Copper', value: 167 },
	{ label: 'Anodized Bronze', value: 168 },
	{ label: 'Anodized Champagne', value: 169 },
	{ label: 'Anodized Gold', value: 170 },
	{ label: 'Green/Blue Flip', value: 171 },
	{ label: 'Green/Red Flip', value: 172 },
	{ label: 'Green/Brown Flip', value: 173 },
	{ label: 'Green/Turquoise Flip', value: 174 },
	{ label: 'Green/Purple Flip', value: 175 },
	{ label: 'Teal/Purple Flip', value: 176 },
	{ label: 'Turquoise/Red Flip', value: 177 },
	{ label: 'Turquoise/Purple Flip', value: 178 },
	{ label: 'Cyan/Purple Flip', value: 179 },
	{ label: 'Blue/Pink Flip', value: 180 },
	{ label: 'Blue/Green Flip', value: 181 },
	{ label: 'Purple/Red Flip', value: 182 },
	{ label: 'Purple/Green Flip', value: 183 },
	{ label: 'Magenta/Green Flip', value: 184 },
	{ label: 'Magenta/Yellow Flip', value: 185 },
	{ label: 'Burgundy/Green Flip', value: 186 },
	{ label: 'Magenta/Cyan Flip', value: 187 },
	{ label: 'Copper/Purple Flip', value: 188 },
	{ label: 'Magenta/Orange Flip', value: 189 },
	{ label: 'Red/Orange Flip', value: 190 },
	{ label: 'Orange/Purple Flip', value: 191 },
	{ label: 'Orange/Blue Flip', value: 192 },
	{ label: 'White/Purple Flip', value: 193 },
	{ label: 'Red/Rainbow Flip', value: 194 },
	{ label: 'Blue/Rainbow Flip', value: 195 },
	{ label: 'Dark Green Pearl', value: 196 },
	{ label: 'Dark Teal Pearl', value: 197 },
	{ label: 'Dark Blue Pearl', value: 198 },
	{ label: 'Dark Purple Pearl', value: 199 },
	{ label: 'Oil Slick Pearl', value: 200 },
	{ label: 'Light Green Pearl', value: 201 },
	{ label: 'Light Blue Pearl', value: 202 },
	{ label: 'Light Purple Pearl', value: 203 },
	{ label: 'Light Pink Pearl', value: 204 },
	{ label: 'Off White Prisma', value: 205 },
	{ label: 'Pink Pearl', value: 206 },
	{ label: 'Yellow Pearl', value: 207 },
	{ label: 'Green Pearl', value: 208 },
	{ label: 'Blue Pearl', value: 209 },
	{ label: 'Cream Pearl', value: 210 },
	{ label: 'White Prismatic', value: 211 },
	{ label: 'Graphite Prismatic', value: 212 },
	{ label: 'Dark Blue Prismatic', value: 213 },
	{ label: 'Dark Purple Prismatic', value: 214 },
	{ label: 'Hot Pink Prismatic', value: 215 },
	{ label: 'Dark Red Prismatic', value: 216 },
	{ label: 'Dark Green Prismatic', value: 217 },
	{ label: 'Black Prismatic', value: 218 },
	{ label: 'Black Oil Spill', value: 219 },
	{ label: 'Black Rainbow', value: 220 },
	{ label: 'Black Holographic', value: 221 },
	{ label: 'White Holographic', value: 222 },
	{ label: 'Monochrome', value: 223 },
	{ label: 'Night & Day', value: 224 },
	{ label: 'The Verlierer', value: 225 },
	{ label: 'Sprunk Extreme', value: 226 },
	{ label: 'Vice City', value: 227 },
	{ label: 'Synthwave Nights', value: 228 },
	{ label: 'Four Seasons', value: 229 },
	{ label: 'Maisonette 9 Throwback', value: 230 },
	{ label: 'Bubblegum', value: 231 },
	{ label: 'Full Rainbow', value: 232 },
	{ label: 'Sunset', value: 233 },
	{ label: 'The Seven', value: 234 },
	{ label: 'Kamen Rider', value: 235 },
	{ label: 'Chromatic Aberration', value: 236 },
	{ label: "It's Christmas!", value: 237 },
	{ label: 'Temperature', value: 238 },
	{ label: 'HSW', value: 239 },
	{ label: 'Electro', value: 240 },
	{ label: 'Monika', value: 241 },
	{ label: 'Fubuki', value: 242 },
]

let pearlescentColor = [
		{ label: 'Black', value: 0 },
		{ label: 'Graphite Black', value: 1 },
		{ label: 'Black Steel', value: 2 },
		{ label: 'Dark Silver', value: 3 },
		{ label: 'Silver', value: 4 },
		{ label: 'Blue Silver', value: 5 },
		{ label: 'Steel Gray', value: 6 },
		{ label: 'Shadow Silver', value: 7 },
		{ label: 'Stone Silver', value: 8 },
		{ label: 'Midnight Silver', value: 9 },
		{ label: 'Gun Metal', value: 10 },
		{ label: 'Anthracite Grey', value: 11 },
		{ label: 'Red', value: 27 },
		{ label: 'Torino Red', value: 28 },
		{ label: 'Formula Red', value: 29 },
		{ label: 'Blaze Red', value: 30 },
		{ label: 'Graceful Red', value: 31 },
		{ label: 'Garnet Red', value: 32 },
		{ label: 'Desert Red', value: 33 },
		{ label: 'Cabernet Red', value: 34 },
		{ label: 'Candy Red', value: 35 },
		{ label: 'Sunrise Orange', value: 36 },
		{ label: 'Classic Gold', value: 37 },
		{ label: 'Orange', value: 38 },
		{ label: 'Dark Green', value: 49 },
		{ label: 'Racing Green', value: 50 },
		{ label: 'Sea Green', value: 51 },
		{ label: 'Olive Green', value: 52 },
		{ label: 'Green', value: 53 },
		{ label: 'Gasoline Green', value: 54 },
		{ label: 'Midnight Blue', value: 61 },
		{ label: 'Dark Blue', value: 62 },
		{ label: 'Saxon Blue', value: 63 },
		{ label: 'Blue', value: 64 },
		{ label: 'Mariner Blue', value: 65 },
		{ label: 'Harbor Blue', value: 66 },
		{ label: 'Diamond Blue', value: 67 },
		{ label: 'Surf Blue', value: 68 },
		{ label: 'Nautical Blue', value: 69 },
		{ label: 'Bright Blue', value: 70 },
		{ label: 'Purple Blue', value: 71 },
		{ label: 'Spinnaker Blue', value: 72 },
		{ label: 'Ultra Blue', value: 73 },
		{ label: 'Bright Blue', value: 74 },
		{ label: 'Taxi Yellow', value: 88 },
		{ label: 'Race Yellow', value: 89 },
		{ label: 'Bronze', value: 90 },
		{ label: 'Yellow Bird', value: 91 },
		{ label: 'Lime', value: 92 },
		{ label: 'Champagne', value: 93 },
		{ label: 'Pueblo Beige', value: 94 },
		{ label: 'Dark Ivory', value: 95 },
		{ label: 'Choco Brown', value: 96 },
		{ label: 'Golden Brown', value: 97 },
		{ label: 'Light Brown', value: 98 },
		{ label: 'Straw Beige', value: 99 },
		{ label: 'Moss Brown', value: 100 },
		{ label: 'Bison Brown', value: 101 },
		{ label: 'Beechwood', value: 102 },
		{ label: 'Dark Beechwood', value: 103 },
		{ label: 'Choco Orange', value: 104 },
		{ label: 'Beach Sand', value: 105 },
		{ label: 'Sun Bleached Sand', value: 106 },
		{ label: 'Cream', value: 107 },
		{ label: 'Ice White', value: 111 },
		{ label: 'Frost White', value: 112 },
		{ label: 'Securicor Green', value: 125 },
		{ label: 'Police Car Blue', value: 127 },
		{ label: 'Pure White', value: 134 },
		{ label: 'Hot Pink', value: 135 },
		{ label: 'Salmon pink', value: 136 },
		{ label: 'Vermillion Pink', value: 137 },
		{ label: 'Orange', value: 138 },
		{ label: 'Green', value: 139 },
		{ label: 'Blue', value: 140 },
		{ label: 'Black Blue', value: 141 },
		{ label: 'Black Purple', value: 142 },
		{ label: 'Black Red', value: 143 },
		{ label: 'Hunter Green', value: 144 },
		{ label: 'Purple', value: 145 },
		{ label: 'V Dark Blue', value: 146 },
		{ label: 'Modshop Black 1', value: 147 },
		{ label: 'Lava Red', value: 150 },
		{ label: 'Default Alloy', value: 156 },
		{ label: 'Epsilon Blue', value: 157 },
]

export const ARMOR = {
	label: 'Armor',
	perms: 'mod',
	dropdown: [
		{
			label: 'Armor',
			option: 'dropdown',
			modAttr: 'modArmor',
			data: [
				{ label: 'No Armor', value: -1 },
				{ label: '20% Armor', value: 0 },
				{ label: '40% Armor', value: 1 },
				{ label: '60% Armor', value: 2 },
				{ label: '80% Armor', value: 3 },
				{ label: '100% Armor', value: 4 },
			],
		},
	],
}
export const BRAKES = {
	label: 'Brakes',
	perms: 'mod',
	dropdown: [
		{
			label: 'Brakes',
			option: 'dropdown',
			modAttr: 'modBrakes',
			data: [
				{ label: 'Standard Brakes', value: -1 },
				{ label: 'Street Brakes', value: 0 },
				{ label: 'Sport Brakes', value: 1 },
				{ label: 'Race Brakes', value: 2 },
			],
		},
	],
}
export const ENGINE = {
	label: 'Engine',
	perms: 'mod',
	dropdown: [
		{
			label: 'Engine',
			option: 'dropdown',
			modAttr: 'modEngine',
			data: [
				{ label: 'Standard Engine', value: -1 },
				{ label: 'EMS Upgrade 1', value: 0 },
				{ label: 'EMS Upgrade 2', value: 1 },
				{ label: 'EMS Upgrade 3', value: 2 },
				{ label: 'EMS Upgrade 4', value: 3 },
			],
		},
	],
}
export const HORN = {
	label: 'Horn',
	perms: 'mod',
	dropdown: [
		{
			label: 'Horn Sound',
			option: 'dropdown',
			modAttr: 'modHorns',
			data: [
				{ label: 'Truck Horn', value: 0 },
				{ label: 'Cop Horn', value: 1 },
				{ label: 'Clown Horn', value: 2 },
				{ label: 'Air Horn 1', value: 52 },
				{ label: 'Air Horn 2', value: 54 },
				{ label: 'Air Horn 3', value: 56 },
				{ label: 'Star Spangled Banner 1', value: 28 },
				{ label: 'Star Spangled Banner 2', value: 29 },
				{ label: 'Star Spangled Banner 3', value: 30 },
				{ label: 'Star Spangled Banner 4', value: 31 },
				{ label: 'Jazz Horn 1', value: 24 },
				{ label: 'Jazz Horn 2', value: 25 },
				{ label: 'Jazz Horn 3', value: 26 },
				{ label: 'Scale - Do', value: 16 },
				{ label: 'Scale - Re', value: 17 },
				{ label: 'Scale - Mi', value: 18 },
				{ label: 'Scale - Fa', value: 19 },
				{ label: 'Scale - Sol', value: 20 },
				{ label: 'Scale - La', value: 21 },
				{ label: 'Scale - Ti', value: 22 },
				{ label: 'Scale - Do (high)', value: 23 },
				{ label: 'Classical Horn 1', value: 9 },
				{ label: 'Classical Horn 2', value: 10 },
				{ label: 'Classical Horn 3', value: 11 },
				{ label: 'Classical Horn 4', value: 12 },
				{ label: 'Classical Horn 5', value: 13 },
				{ label: 'Classical Horn 6', value: 14 },
				{ label: 'Classical Horn 7', value: 15 },
				{ label: 'Classical Horn 8', value: 33 },
				{ label: 'Musical Horn 1', value: 3 },
				{ label: 'Musical Horn 2', value: 4 },
				{ label: 'Musical Horn 3', value: 5 },
				{ label: 'Musical Horn 4', value: 6 },
				{ label: 'Musical Horn 5', value: 7 },
				{ label: 'Sad Trombone', value: 8 },
				{ label: 'Festive Bells 1', value: 47 },
				{ label: 'Festive Bells 2', value: 49 },
				{ label: 'Festive Bells 3', value: 51 },
				{ label: 'Jazz Horn Loop', value: 27 },
				{ label: 'Classical Horn Loop 1', value: 32 },
				{ label: 'Classical Horn Loop 2', value: 34 },
				{ label: 'San Andreas Loop', value: 42 },
				{ label: 'Liberty City Loop', value: 44 },
				{ label: 'Halloween Loop 1', value: 38 },
				{ label: 'Halloween Loop 2', value: 40 },
				{ label: 'Festive Loop 1', value: 46 },
				{ label: 'Festive Loop 2', value: 48 },
				{ label: 'Festive Loop 3', value: 50 },
			],
		},
	],
}
export const LIGHTS = {
	label: 'Lights',
	perms: 'mod',
	dropdown: [
		{
			label: 'Headlights',
			option: 'dropdown',
			modType: 22,
			data: [
				{ label: 'Standard Headlights', value: '-1' },
				{ label: 'Xeon Headlights', value: '0' },
			],
		},
	],
}
export const PLATES = {
	label: 'Plates',
	perms: 'mod',
	dropdown: [
		{
			label: 'Number Plate Style',
			option: 'dropdown',
			modAttr: 'plateIndex',
			data: [
				{ label: 'Style 1', value: 0 },
				{ label: 'Style 2', value: 1 },
				{ label: 'Style 3', value: 2 },
				{ label: 'Style 4', value: 3 },
				{ label: 'Style 5', value: 4 },
				{ label: 'Style 6', value: 5 },
			],
		},
		{ label: 'Number Plate', option: 'text', modAttr: 'modPlate' },
	],
}
export const RESPRAY_PRIMARY = {
	label: 'Respray Primary Color',
	perms: 'mod',
	dropdown: [
		{
			label: 'Primary Color',
			option: 'dropdown',
			modAttr: 'color1',
			data: colors,
		},
		{
			label: 'Primary Colorpicker',
			option: 'colorpicker',
			modAttr: 'color1',
			data: []
		},
	],
}
export const RESPRAY_SECONDARY = {
	label: 'Respray Secondary Color',
	perms: 'mod',
	dropdown: [
		{
			label: 'Secondary Color',
			option: 'dropdown',
			modAttr: 'color2',
			data: colors,
		},
		{
			label: 'Secondary Colorpicker',
			option: 'colorpicker',
			modAttr: 'color2',
			data: []
		},

	],
}
export const RESPRAY_PEARLESCENT = {
	label: 'Respray Pearlescent Color',
	perms: 'mod',
	dropdown: [
		{
			label: 'Pearlescent Color',
			option: 'dropdown',
			modAttr: 'pearlescentColor',
			data: pearlescentColor,
		},
	],
}
export const SUSPENSION = {
	label: 'Suspension',
	perms: 'mod',
	dropdown: [
		{
			label: 'Suspension',
			option: 'dropdown',
			modAttr: 'modSuspension',
			data: [
				{ label: 'Standard Suspension', value: -1 },
				{ label: 'Lower Suspension', value: 0 },
				{ label: 'Street Suspension', value: 1 },
				{ label: 'Sport Suspension', value: 2 },
				{ label: 'Race Suspension', value: 3 },
			],
		},
	],
}
export const TRANSMISSION = {
	label: 'Transmission',
	perms: 'mod',
	dropdown: [
		{
			label: 'Transmission',
			option: 'dropdown',
			modAttr: 'modTransmission',
			data: [
				{ label: 'Standard Transmission', value: -1 },
				{ label: 'Street Transmission', value: 0 },
				{ label: 'Sport Transmission', value: 1 },
				{ label: 'Race Transmission', value: 2 },
			],
		},
	],
}
export const TURBO = {
	label: 'Turbo',
	perms: 'mod',
	dropdown: [
		{
			label: 'Turbo',
			option: 'dropdown',
			modAttr: 'modTurbo',
			data: [
				{ label: 'Disabled', value: -1 },
				{ label: 'Enabled', value: 0 },
			],
		},
	],
}
export const WINDOWS = {
	label: 'Windows',
	perms: 'mod',
	dropdown: [
		{
			label: 'Tint',
			option: 'dropdown',
			modAttr: 'windowTint',
			data: [
				{ label: 'None', value: -1 },
				{ label: 'Light Smokeglass', value: 0 },
				{ label: 'Dark Smokeglass', value: 1 },
				{ label: 'Limousine', value: 2 },
			],
		},
	],
}

export const WHEELS = {
	label: 'Wheels',
	perms: 'mod',
	dropdown: [
		{
			label: 'Wheel Color',
			option: 'dropdown',
			modAttr: 'wheelColor',
			data: colors,
		},
	],
}